AWSTemplateFormatVersion: "2010-09-09"
Description: "Parent stack for deploying VPC, EC2, and VPN Gateway"

Parameters:
  Environment:
    Type: String
    Description: The environment name (e.g., development, production)
    AllowedValues:
      - development
      - production
      - default

  VPCStackURL:
    Type: String
    Description: The URL for the VPC Template

  EC2StackURL:
    Type: String
    Description: "The URL for the EC2 Template"

  VGWStackURL:
    Type: String
    Description: "The URL for the VPN Gateway Template"

  PreSharedKey:
    Type: String
    Description: "The PSK used to establish the VPN connection (Passed down to the VGW Stack)"
    NoEcho: true

Resources:
  # Deploying the VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VPCStackURL
      Parameters:
        Environment: !Ref Environment
      TimeoutInMinutes: 10

  EC2Stack:
    # Deploying the EC2 Stack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref EC2StackURL
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        VPCCIDR: !GetAtt VPCStack.Outputs.VPCCIDR
        Environment: !Ref Environment
      TimeoutInMinutes: 10

  VGWStack:
    # Deploying the VGW Stack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VGWStackURL
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        PreSharedKey: !Ref PreSharedKey
        Environment: !Ref Environment
      TimeoutInMinutes: 10